version: 2
jobs:
  Authentication-User:
    working_directory: ~/poc
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 
          command: |
            touch userinfo.txt
            curl https://circleci.com/api/v1.1/me?circle-token=936c2e6bb9fa6c0fbe29db3622c77b12f5701f01 >> userinfo.txt
            cat userinfo.txt
            if [[ $APPROVER == $SUPER_USER1 || $APPROVER == $SUPER_USER2 ]]; then
            echo user is authrized
            else
            echo user is not authorized 
            exit 1
            fi
            
  Dev-Build:
    working_directory: ~/poc
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 
          command: |
            echo "This is dev build"
workflows:
  version: 2
  poc-workflow:
    jobs:
      - Dev-Build:
          filters:
            branches:
              only: # this workflow won't run for branches matching the below regex
                - /^hotfix.*/
      - Deploy-To-Prod:
          type: approval
          requires:
            - Dev-Build
      - Authentication-User:
          requires:
            - Deploy-To-Prod
          context: super_user
